services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: my-web-app:latest
    depends_on:
      - backend
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: my-backend-app:latest
    ports:
      - "9000:5252"
